/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : CommentId,
  'content' : string,
  'author' : UserId,
  'timestamp' : bigint,
}
export type CommentId = string;
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : MessageId,
  'content' : string,
  'recipient' : UserId,
  'isRead' : boolean,
  'sender' : UserId,
  'timestamp' : bigint,
}
export type MessageId = string;
export interface Notification {
  'id' : NotificationId,
  'content' : string,
  'userId' : UserId,
  'isRead' : boolean,
  'timestamp' : bigint,
}
export type NotificationId = string;
export interface Post {
  'id' : PostId,
  'media' : Array<ExternalBlob>,
  'content' : string,
  'author' : UserId,
  'likes' : Array<UserId>,
  'timestamp' : bigint,
  'comments' : Array<Comment>,
  'visibility' : Visibility,
}
export type PostId = string;
export interface Report {
  'id' : ReportId,
  'reportedPost' : [] | [PostId],
  'reportedUser' : [] | [UserId],
  'timestamp' : bigint,
  'reporter' : UserId,
  'reason' : string,
}
export type ReportId = string;
export interface Story {
  'id' : StoryId,
  'media' : ExternalBlob,
  'expiresAt' : bigint,
  'author' : UserId,
  'timestamp' : bigint,
}
export type StoryId = string;
export type UserId = Principal;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'followers' : Array<UserId>,
  'following' : Array<UserId>,
  'visibility' : Visibility,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Visibility = { 'pub' : null } |
  { 'priv' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'commentOnPost' : ActorMethod<[PostId, string], CommentId>,
  'createNotification' : ActorMethod<[UserId, string], NotificationId>,
  'createPost' : ActorMethod<[string, Array<ExternalBlob>, Visibility], PostId>,
  'createStory' : ActorMethod<[ExternalBlob], StoryId>,
  'deletePost' : ActorMethod<[PostId], undefined>,
  'followUser' : ActorMethod<[UserId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFollowers' : ActorMethod<[UserId], Array<UserId>>,
  'getFollowing' : ActorMethod<[UserId], Array<UserId>>,
  'getMessages' : ActorMethod<[UserId], Array<Message>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPublicPosts' : ActorMethod<[], Array<Post>>,
  'getReports' : ActorMethod<[], Array<Report>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUserStories' : ActorMethod<[UserId], Array<Story>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'markMessageAsRead' : ActorMethod<[MessageId, UserId], undefined>,
  'markNotificationAsRead' : ActorMethod<[NotificationId], undefined>,
  'reportContent' : ActorMethod<
    [[] | [UserId], [] | [PostId], string],
    ReportId
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<UserProfile>>,
  'sendMessage' : ActorMethod<[UserId, string], MessageId>,
  'unfollowUser' : ActorMethod<[UserId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];