/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostId = IDL.Text;
export const CommentId = IDL.Text;
export const UserId = IDL.Principal;
export const NotificationId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Visibility = IDL.Variant({ 'pub' : IDL.Null, 'priv' : IDL.Null });
export const StoryId = IDL.Text;
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'followers' : IDL.Vec(UserId),
  'following' : IDL.Vec(UserId),
  'visibility' : Visibility,
});
export const MessageId = IDL.Text;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'recipient' : UserId,
  'isRead' : IDL.Bool,
  'sender' : UserId,
  'timestamp' : IDL.Int,
});
export const Notification = IDL.Record({
  'id' : NotificationId,
  'content' : IDL.Text,
  'userId' : UserId,
  'isRead' : IDL.Bool,
  'timestamp' : IDL.Int,
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'content' : IDL.Text,
  'author' : UserId,
  'timestamp' : IDL.Int,
});
export const Post = IDL.Record({
  'id' : PostId,
  'media' : IDL.Vec(ExternalBlob),
  'content' : IDL.Text,
  'author' : UserId,
  'likes' : IDL.Vec(UserId),
  'timestamp' : IDL.Int,
  'comments' : IDL.Vec(Comment),
  'visibility' : Visibility,
});
export const ReportId = IDL.Text;
export const Report = IDL.Record({
  'id' : ReportId,
  'reportedPost' : IDL.Opt(PostId),
  'reportedUser' : IDL.Opt(UserId),
  'timestamp' : IDL.Int,
  'reporter' : UserId,
  'reason' : IDL.Text,
});
export const Story = IDL.Record({
  'id' : StoryId,
  'media' : ExternalBlob,
  'expiresAt' : IDL.Int,
  'author' : UserId,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'commentOnPost' : IDL.Func([PostId, IDL.Text], [CommentId], []),
  'createNotification' : IDL.Func([UserId, IDL.Text], [NotificationId], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Vec(ExternalBlob), Visibility],
      [PostId],
      [],
    ),
  'createStory' : IDL.Func([ExternalBlob], [StoryId], []),
  'deletePost' : IDL.Func([PostId], [], []),
  'followUser' : IDL.Func([UserId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getMessages' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPublicPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getUserStories' : IDL.Func([UserId], [IDL.Vec(Story)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'markMessageAsRead' : IDL.Func([MessageId, UserId], [], []),
  'markNotificationAsRead' : IDL.Func([NotificationId], [], []),
  'reportContent' : IDL.Func(
      [IDL.Opt(UserId), IDL.Opt(PostId), IDL.Text],
      [ReportId],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'sendMessage' : IDL.Func([UserId, IDL.Text], [MessageId], []),
  'unfollowUser' : IDL.Func([UserId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostId = IDL.Text;
  const CommentId = IDL.Text;
  const UserId = IDL.Principal;
  const NotificationId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Visibility = IDL.Variant({ 'pub' : IDL.Null, 'priv' : IDL.Null });
  const StoryId = IDL.Text;
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'followers' : IDL.Vec(UserId),
    'following' : IDL.Vec(UserId),
    'visibility' : Visibility,
  });
  const MessageId = IDL.Text;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'recipient' : UserId,
    'isRead' : IDL.Bool,
    'sender' : UserId,
    'timestamp' : IDL.Int,
  });
  const Notification = IDL.Record({
    'id' : NotificationId,
    'content' : IDL.Text,
    'userId' : UserId,
    'isRead' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'content' : IDL.Text,
    'author' : UserId,
    'timestamp' : IDL.Int,
  });
  const Post = IDL.Record({
    'id' : PostId,
    'media' : IDL.Vec(ExternalBlob),
    'content' : IDL.Text,
    'author' : UserId,
    'likes' : IDL.Vec(UserId),
    'timestamp' : IDL.Int,
    'comments' : IDL.Vec(Comment),
    'visibility' : Visibility,
  });
  const ReportId = IDL.Text;
  const Report = IDL.Record({
    'id' : ReportId,
    'reportedPost' : IDL.Opt(PostId),
    'reportedUser' : IDL.Opt(UserId),
    'timestamp' : IDL.Int,
    'reporter' : UserId,
    'reason' : IDL.Text,
  });
  const Story = IDL.Record({
    'id' : StoryId,
    'media' : ExternalBlob,
    'expiresAt' : IDL.Int,
    'author' : UserId,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'commentOnPost' : IDL.Func([PostId, IDL.Text], [CommentId], []),
    'createNotification' : IDL.Func([UserId, IDL.Text], [NotificationId], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Vec(ExternalBlob), Visibility],
        [PostId],
        [],
      ),
    'createStory' : IDL.Func([ExternalBlob], [StoryId], []),
    'deletePost' : IDL.Func([PostId], [], []),
    'followUser' : IDL.Func([UserId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getMessages' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPublicPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getUserStories' : IDL.Func([UserId], [IDL.Vec(Story)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'markMessageAsRead' : IDL.Func([MessageId, UserId], [], []),
    'markNotificationAsRead' : IDL.Func([NotificationId], [], []),
    'reportContent' : IDL.Func(
        [IDL.Opt(UserId), IDL.Opt(PostId), IDL.Text],
        [ReportId],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'sendMessage' : IDL.Func([UserId, IDL.Text], [MessageId], []),
    'unfollowUser' : IDL.Func([UserId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };